### ISSUE TITLE
How to use Proxy in the chatgpt-python?

### ISSUE THREAD

**Issue by houzhong** [labteral/chatgpt-python#5]
Some countries like China, Hk,   They need proxy access to chatgpt
How to use a proxy in chatgpt-python like socks5, http proxy and so on.

**Comment by kangming06** [comment]
![image](https://user-images.githubusercontent.com/74850890/206454320-785f3b0f-5248-434c-9639-1687ff3d7f94.png)
Modify ***\chatgpt\chatgpt.py like this.

**Comment by brunneis** [comment]
Hi @houzhong,

While this is not implemented in the code, you can try setting the following environment variables before using the library:

```
export HTTP_PROXY="http://<user>:<pass>@<proxy>:<port>"
export HTTPS_PROXY="http://<user>:<pass>@<proxy>:<port>"
```
