### ISSUE TITLE
Copyright and licensing issues

### ISSUE THREAD

**Issue by rawandahmad698** [labteral/chatgpt-python#7]
Hello.

It seems like you have copied code from https://github.com/rawandahmad698/PyChatGPT/blob/master/src/pychatgpt/classes/openai.py & https://github.com/rawandahmad698/PyChatGPT/blob/master/src/pychatgpt/classes/openai.py#L128 
[Here](https://github.com/labteral/chatgpt-python/blob/master/chatgpt/chatgpt.py#L42) Additionally, You have stolen 4-6 days of work on finding the right steps, using the right tools. Without proper licensing/crediting. 
to mask this, you also invoke a private function in tls-client [here](https://github.com/FlorianREGAZ/Python-Tls-Client/blob/master/tls_client/sessions.py#L213) And I'd like to remind you that tls-client is also licensed in MIT. 

https://github.com/FlorianREGAZ/Python-Tls-Client/blob/master/LICENSE
https://github.com/rawandahmad698/PyChatGPT/blob/master/LICENSE

PyChatGPT is licensed under MIT, This would mean that you 
> The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

Please also credit the original source. Failing to do so will result in a Takedown Strike

To whom it may concern,

I, Rawand Ahmed Shaswar, am writing to report an instance of copyright infringement. I am the owner and creator of the copyrighted work "PyChatGPT," which is a Python module that allows users to automate the regeneration of access tokens for the ChatGPT service. This work is available on GitHub at [https://github.com/rawandahmad698/PyChatGPT/blob/master/src/pychatgpt/classes/openai.py#L73] and is licensed under the MIT license.

It has come to my attention that my work has been copied and published without attribution by a user on GitHub under the username @labteral. The infringing work, which can be found at [https://github.com/labteral/chatgpt-python/blob/master/chatgpt/chatgpt.py#L42], includes modifications to the original code, such as renamed variables and functions, but the overall structure and methods used in the code remain the same as my original work.

I have made attempts to contact @labteral and resolve this issue, but he has not responded. I am therefore requesting that the infringing work be removed and that @labteral be required to attribute the original work to me and include a copy of the MIT license in any future publications of the code.

I swear, under penalty of perjury, that the information in this notice is accurate and that I am the owner or am authorized to act on behalf of the owner of an exclusive right that is allegedly infringed.

Sincerely,
Rawand Ahmed Shaswar

Date: 1670520017

**Comment by acheong08** [comment]
I can corroborate this. The authentication code here is most definitely plagiarized from @rawandahmad698

**Comment by diogogosch** [comment]
this is false, I have copied a total of 0 characters of code from you

**Comment by acheong08** [comment]
@rawandahmad698 labtera is spelled incorrectly. It's @labteral

**Comment by rawandahmad698** [comment]
Thanks, Edited

**Comment by CharlyWargnier** [comment]
I can see I am mentioned here.

What do I need to do to fix this?

Do I need to fully remove this library from my Github, or are there workarounds?

Thanks,
Charly

**Comment by rawandahmad698** [comment]
> I can see I am mentioned here.
> 
> What do I need to do to fix this?
> 
> Do I need to fully remove this library from my Github, or are there workarounds?
> 
> Thanks, Charly

Dear Charly,

Thank you for your reply. I appreciate that you are willing to address this issue.

As the owner and creator of the copyrighted work "PyChatGPT," it is important to me that my work is attributed and that the appropriate license is included in any future publications of the code. The original work can be found at [https://github.com/rawandahmad698/PyChatGPT/blob/master/src/pychatgpt/classes/openai.py#L73] and is licensed under the MIT license.

To address this issue, I ask that you attribute the original work to me and include a copy of the MIT license in any future publications of the code. I also ask that you remove the infringing work from your GitHub repository, as using someone else's work without permission or attribution is a violation of copyright law.

It is up to you to decide whether to fully remove the library or find a workaround that does not violate my copyright. If you have any questions or concerns, please do not hesitate to contact me.

Sincerely,
Rawand Ahmed Shaswar
pychatgpt@rawa.dev
